"
Second-order ADAA acos().

The domain of this function is [-1.0; 1.0]; its theoretical range is [π; 0.0].

Note that this function is not accurate for low-amplitude or low-frequency input signals. In that case, the first-order ADAA arccos() can be used.
"
Class {
	#name : 'ArcCos2',
	#superclass : 'Trigonometry',
	#category : 'Phausto-Antialiased',
	#package : 'Phausto',
	#tag : 'Antialiased'
}
