"
First implementation of Box API for Phausto, deprecated
"
Class {
	#name : 'ManifestPhausto',
	#superclass : 'PackageManifest',
	#category : 'Phausto-Manifest',
	#package : 'Phausto',
	#tag : 'Manifest'
}

{ #category : 'code-critics' }
ManifestPhausto class >> ruleAssignmentInIfTrueRuleV1FalsePositive [

	<ignoreForCoverage>
	^ #(#(#(#RGMethodDefinition #(#FluteModel #mouthPosition: #false)) #'2024-08-05T15:19:53.278305+02:00') )
]
