"
Set the parameters variable of the UnitGenerator to a PhBox, or changes its labels, or set its initialized value
"
Trait {
	#name : 'ParamsSetter',
	#category : 'Phausto-Traits',
	#package : 'Phausto',
	#tag : 'Traits'
}

{ #category : 'accessing' }
ParamsSetter >> aN: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> accent: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> amount: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> amplitude: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> ar: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> attack: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> attenuation: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> b0: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> bM: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> biasAttack: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> biasDecay: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> biasRelease: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> bowPosition: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> bowPressure: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> bowVelocity: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> breathGain: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> captureButton: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> cent: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> clockDivider: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> condition: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> crossfade: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> curdel: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> cutoff: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> cutoffFreq: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> damp: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> decay: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> del: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> delayLength: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> depth: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> dmax: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> drive: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> dsfreq: aNumberOrABoxOrASymbol [


	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> duration: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> duty: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> earlyDiff: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> else: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> envMod: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> excitation: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> fb1: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> fb2: aNumberOrABoxOrASymbol [
self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> fb: aNumberOrABoxOrASymbol [

self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> fbff: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> feedBack: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> finalLevel: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> fr: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> freq: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> frequency: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> fund: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> g: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> gain: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> gate: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> hpCutoff: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> impulseIndex: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> index: aNumberOrABoxOrASymbol [


	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> init: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> input1: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> input2: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> input: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> inputL: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> inputR: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> intDel: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> interpControl: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> interpolationTime: aNumberOrABoxOrASymbol [

self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> invert: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> legato: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> length: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> level1: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> level2: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> level3: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> level4: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> level: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> link: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> lpCutoff: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> max: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> maxDel: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> maxFreq: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> midiNN: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> min: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> modDepth: aNumberOrABoxOrASymbol [

self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> modFreq: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> modIndex: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> modRatio: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> mode: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> n: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> normFreq: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> numberOfBands: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> offset: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> pan: aNumberOrABoxOrASymbol [

self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'helper' }
ParamsSetter >> paramSetter [
    | paramName |
    paramName := thisContext sender method selector allButLast.
    ^ [ :value | value asParam: paramName forUGen: self ]
]

{ #category : 'accessing' }
ParamsSetter >> period: aNumberOrABoxOrASymbol [

	| methodName |
	methodName := thisContext selector. "Get the name of this method"

	methodName asString allButLast traceCr.
	aNumberOrABoxOrASymbol
		asParam: methodName asString allButLast
		forUGen: self
]

{ #category : 'accessing' }
ParamsSetter >> pickupPosition: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> pitch: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> pluckPosition: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> pole: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> poles: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> pressure: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> q: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> release1: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> release2: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> release3: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> release4: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> release: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> res: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> resonance: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> run: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> scSignal: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> scSwitch: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> semitone: aNumberOrABoxOrASymbol [

self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> shift: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> signal: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> size: aNumberOrABoxOrASymbol [

self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> source: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> spread: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> strikeCutoff: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> strikePosition: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> strikeSharpness: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> stringLength: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> sustain: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> t60: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> tau: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> tempo: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> then: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> threshLim: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> threshold: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> tone: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> totalImpulses: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> trig: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> trigger: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> tuning: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> volume: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> wah: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> waveform: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> wetAmount: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'accessing' }
ParamsSetter >> window: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]
