"
ADSR related parameter setters
"
Trait {
	#name : 'PhADSRSetter',
	#category : 'Phausto-Traits',
	#package : 'Phausto',
	#tag : 'Traits'
}

{ #category : 'trait - envelopes' }
PhADSRSetter >> ar: aNumberOrABoxOrASymbol [

	PhPsImpl paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - envelopes' }
PhADSRSetter >> attack: aNumberOrABoxOrASymbol [

	PhPsImpl paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - envelopes' }
PhADSRSetter >> decay: aNumberOrABoxOrASymbol [

	PhPsImpl paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - envelopes' }
PhADSRSetter >> level1: aNumberOrABoxOrASymbol [

	PhPsImpl paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - envelopes' }
PhADSRSetter >> level2: aNumberOrABoxOrASymbol [

	PhPsImpl paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - envelopes' }
PhADSRSetter >> level3: aNumberOrABoxOrASymbol [

	PhPsImpl paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - envelopes' }
PhADSRSetter >> level4: aNumberOrABoxOrASymbol [

	PhPsImpl paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - envelopes' }
PhADSRSetter >> release1: aNumberOrABoxOrASymbol [

PhPsImpl paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - envelopes' }
PhADSRSetter >> release2: aNumberOrABoxOrASymbol [

	PhPsImpl paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - envelopes' }
PhADSRSetter >> release3: aNumberOrABoxOrASymbol [

	PhPsImpl paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - envelopes' }
PhADSRSetter >> release4: aNumberOrABoxOrASymbol [

	PhPsImpl paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - envelopes' }
PhADSRSetter >> release: aNumberOrABoxOrASymbol [

	PhPsImpl paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhADSRSetter >> sustain: aNumberOrABoxOrASymbol [

	PhPsImpl paramSetter value: aNumberOrABoxOrASymbol
]
