"
Useful setters for interpolators
"
Trait {
	#name : 'PhInterpSetter',
	#category : 'Phausto-Traits',
	#package : 'Phausto',
	#tag : 'Traits'
}

{ #category : 'trait' }
PhInterpSetter >> dv: aNumberOrABoxOrASymbol [

	PhPsImpl paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - interpolators' }
PhInterpSetter >> length: aNumberOrABoxOrASymbol [

	PhPsImpl paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - interpolators' }
PhInterpSetter >> step: aNumberOrABoxOrASymbol [

	PhPsImpl paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - interpolators' }
PhInterpSetter >> trig: aNumberOrABoxOrASymbol [

	PhPsImpl paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - interpolators' }
PhInterpSetter >> v0: aNumberOrABoxOrASymbol [

	PhPsImpl paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - interpolators' }
PhInterpSetter >> v1: aNumberOrABoxOrASymbol [

	PhPsImpl paramSetter value: aNumberOrABoxOrASymbol
]
