"
Set the parameters variable of the UnitGenerator to a PhBox, or changes its labels, or set its initialized value
"
Trait {
	#name : 'PhParamsSetter',
	#category : 'Phausto-Traits',
	#package : 'Phausto',
	#tag : 'Traits'
}

{ #category : 'trait' }
PhParamsSetter >> aN: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> accent: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> amount: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> amplitude: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - envelopes' }
PhParamsSetter >> ar: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - envelopes' }
PhParamsSetter >> attack: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> attenuation: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> b0: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> b: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> bM: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - physModels' }
PhParamsSetter >> bellOpening: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> biasAttack: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> biasDecay: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> biasRelease: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> blend: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> bowPosition: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> bowPressure: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> bowVelocity: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> breathGain: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> captureButton: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> cent: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - cutoff' }
PhParamsSetter >> clockDivider: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> condition: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> crossfade: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> curdel: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - cutoff' }
PhParamsSetter >> cutoff: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - cutoff' }
PhParamsSetter >> cutoffFreq: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> damp: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> decay: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> del: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> delayLength: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> density: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> depth: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> dmax: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> drive: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> dsfreq: aNumberOrABoxOrASymbol [


	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> dt: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> duration: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> duty: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> dv: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> dwell: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> earlyDiff: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> else: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> envMod: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> excitation: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> fb1: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> fb2: aNumberOrABoxOrASymbol [
self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> fb: aNumberOrABoxOrASymbol [

self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> fbff: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> feedBack: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> finalLevel: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> fr: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> freq: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - freq' }
PhParamsSetter >> frequency: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> fund: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> fx: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> g: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> gain: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - envelopes' }
PhParamsSetter >> gate: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - cutoff' }
PhParamsSetter >> hpCutoff: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> impulseIndex: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> index: aNumberOrABoxOrASymbol [


	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> init: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - inputs' }
PhParamsSetter >> input1: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - inputs' }
PhParamsSetter >> input2: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - inputs' }
PhParamsSetter >> input: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - inputs' }
PhParamsSetter >> inputL: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - inputs' }
PhParamsSetter >> inputR: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> intDel: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> interpControl: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> interpolationTime: aNumberOrABoxOrASymbol [

self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> invert: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> legato: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> length: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - envelopes' }
PhParamsSetter >> level1: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - envelopes' }
PhParamsSetter >> level2: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - envelopes' }
PhParamsSetter >> level3: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - envelopes' }
PhParamsSetter >> level4: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> level: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> lfx: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> link: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> lipsTension: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> lpCutoff: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> max: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> maxDel: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> maxDuration: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> maxFreq: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> midiNN: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> min: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> modDepth: aNumberOrABoxOrASymbol [

self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> modFreq: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> modIndex: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> modRatio: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> mode: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> n: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> nMax: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> nonLinearity: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> normFreq: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> numberOfBands: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> offset: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> pan: aNumberOrABoxOrASymbol [

self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'helper' }
PhParamsSetter >> paramSetter [
    | paramName |
    paramName := thisContext sender method selector allButLast.
    ^ [ :value | value asParam: paramName forUGen: self ]
]

{ #category : 'trait' }
PhParamsSetter >> part: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> period: aNumberOrABoxOrASymbol [

	| methodName |
	methodName := thisContext selector. "Get the name of this method"

	methodName asString allButLast traceCr.
	aNumberOrABoxOrASymbol
		asParam: methodName asString allButLast
		forUGen: self
]

{ #category : 'trait' }
PhParamsSetter >> pickupPosition: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> pitch: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> pluckPosition: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> pole: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> poles: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - physModels' }
PhParamsSetter >> pressure: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> q: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - physModels' }
PhParamsSetter >> reedStiffness: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - envelopes' }
PhParamsSetter >> release1: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - envelopes' }
PhParamsSetter >> release2: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - envelopes' }
PhParamsSetter >> release3: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - envelopes' }
PhParamsSetter >> release4: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - envelopes' }
PhParamsSetter >> release: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> res: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> reset: aNumberOrABoxOrASymbol [

		self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> resonance: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> run: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> scSignal: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> scSwitch: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> semitone: aNumberOrABoxOrASymbol [

self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> shift: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> signal: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> size: aNumberOrABoxOrASymbol [

self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> slope:  aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> smoothness: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> source: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> spread: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> springs: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> start:  aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - physModels' }
PhParamsSetter >> stiffness: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> strikeCutoff: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> strikePosition: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> strikeSharpness: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> stringLength: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> sustain: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - envelopes' }
PhParamsSetter >> t60: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> tN: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> tau: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> tempo: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> tension: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> then: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> threshLim: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> threshold: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> tone: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> totalImpulses: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - physModels' }
PhParamsSetter >> tubeLength: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> tuning: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - interpolators' }
PhParamsSetter >> v0: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait - interpolators' }
PhParamsSetter >> v1: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> volume: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> wah: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> waveform: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> wetAmount: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]

{ #category : 'trait' }
PhParamsSetter >> window: aNumberOrABoxOrASymbol [

	self paramSetter value: aNumberOrABoxOrASymbol
]
