"
This class contains a collection of synthesizers, including those of Faust synths.lib

** Do not use this superclass directly; it exists only for grouping and establishing a basic inheritance chain. Use one of its subclasses instead.**
"
Class {
	#name : 'Synths',
	#superclass : 'UnitGenerator',
	#category : 'Phausto-Synths',
	#package : 'Phausto',
	#tag : 'Synths'
}

{ #category : 'initialization' }
Synths >> initialize [

	super initialize.
	
]
